import { readFile, mkdir, writeFile } from 'node:fs/promises';
const base = new URL('../', import.meta.url);
const source = await Promise.all(['core.js', 'extractor.js', 'snapshot.js'].map(name => readFile(new URL('src/main/js/' + name, base), 'utf8')));
const code = source.map(s => s.replace(/^export \{[^\n]+\};?\s*$/gm, '').replace(/^export function /gm, 'function ')).join('\n');
await mkdir(new URL('src/main/assets/', base), { recursive: true });
await writeFile(new URL('src/main/assets/probe.js', base), '/* Generated by reader/scripts/build-reader.mjs. */\n(() => {\n' + code + '\nreturn JSON.stringify(readSnapshot());\n})()');
